
// Generated by delombok at Fri Mar 20 22:19:47 CET 2020
package edu.msudenver.cs.jdnss;

enum ErrorCodes {
    NOERROR(0), FORMERROR(1), SERVFAIL(2), NAMEERROR(3), NOTIMPL(4), REFUSED(5), YXRRSET(7);
    final int code;

    ErrorCodes(int code) {
        this.code = code;
    }

    @java.lang.SuppressWarnings("all")
    public int getCode() {
        return this.code;
    }
}